// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET home page. */

  router.get('/', function(req, res, next) {
    res.render('admin', {
      title: 'Admin'
    });
  });

  module.exports = router;

}).call(this);
