// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET home page. */

  router.get('/:name', function(req, res) {
    var name;
    name = req.params.name;
    res.render('partials/' + name);
  });

  module.exports = router;

}).call(this);
